[2025-03-31 23:21:31,009: INFO: main: Welcome to our custom log]
[2025-04-01 22:56:56,892: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-01 22:56:56,920: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-01 22:56:56,938: INFO: common: created directory at: artifacts]
[2025-04-01 22:56:56,955: INFO: common: created directory at: data_ingestion]
[2025-04-01 22:56:56,976: INFO: 1120952329: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-01 22:59:00,037: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-01 22:59:00,041: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-01 22:59:00,043: INFO: common: created directory at: artifacts]
[2025-04-01 22:59:00,044: INFO: common: created directory at: data_ingestion]
[2025-04-01 22:59:00,048: INFO: 1120952329: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-01 23:02:14,805: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-01 23:02:14,810: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-01 23:02:14,812: INFO: common: created directory at: artifacts]
[2025-04-01 23:02:14,817: INFO: common: created directory at: data_ingestion]
[2025-04-01 23:02:14,825: INFO: 1120952329: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-01 23:09:28,819: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-01 23:09:28,824: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-01 23:09:28,827: INFO: common: created directory at: artifacts]
[2025-04-01 23:09:28,830: INFO: common: created directory at: data_ingestion]
[2025-04-01 23:09:28,834: INFO: 1626317731: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-01 23:44:26,140: INFO: 1626317731: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-01 23:44:27,956: INFO: 1626317731: File extracted successfully to artifacts/data_ingestion]
[2025-04-02 08:18:48,788: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-02 08:18:48,791: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-02 08:18:48,793: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-02 08:18:48,795: INFO: common: created directory at: artifacts]
[2025-04-02 08:18:48,797: INFO: common: created directory at: data_ingestion]
[2025-04-02 08:18:48,798: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-02 08:37:00,610: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-02 08:37:02,620: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-02 08:37:02,621: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 19:53:46,307: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 19:53:46,321: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 19:54:01,324: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 19:54:01,326: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 19:54:18,547: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 19:54:18,549: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 19:55:23,297: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 19:55:23,303: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:00:03,330: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 21:00:03,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:00:03,347: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:00:03,349: INFO: common: created directory at: artifacts]
[2025-04-11 21:00:03,349: INFO: common: created directory at: data_ingestion]
[2025-04-11 21:00:03,350: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 21:17:50,718: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 21:17:50,719: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:17:50,720: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:17:50,721: INFO: common: created directory at: artifacts]
[2025-04-11 21:17:50,721: INFO: common: created directory at: data_ingestion]
[2025-04-11 21:17:50,721: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 21:17:50,727: ERROR: data_ingestion: Error downloading file: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1e3q72lfBRd5KX8KulVX39q34vW3y2M2b (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018CFFC5CFB0>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))]
[2025-04-11 21:17:50,729: ERROR: data_ingestion: Error extracting file: Zip file not found: artifacts/data_ingestion/data.zip]
[2025-04-11 21:17:50,729: ERROR: main: Zip file not found: artifacts/data_ingestion/data.zip]
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.extract_zip_file()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 49, in extract_zip_file
    raise e
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 40, in extract_zip_file
    raise FileNotFoundError(f"Zip file not found: {self.config.local_data_file}")
FileNotFoundError: Zip file not found: artifacts/data_ingestion/data.zip
[2025-04-11 21:18:32,089: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 21:18:32,091: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:18:32,092: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:18:32,093: INFO: common: created directory at: artifacts]
[2025-04-11 21:18:32,093: INFO: common: created directory at: data_ingestion]
[2025-04-11 21:18:32,093: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 21:20:47,390: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 21:20:48,184: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 21:20:48,184: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 21:20:52,516: INFO: main: *******************]
[2025-04-11 21:20:52,516: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 21:20:52,517: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:20:52,518: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:20:52,519: INFO: common: created directory at: artifacts]
[2025-04-11 21:20:52,520: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 21:20:52,520: ERROR: main: "'ConfigBox' object has no attribute 'include_top'"]
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'INCLUDE_TOP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'INCLUDE_TOP'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'INCLUDE_TOP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'INCLUDE_TOP'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'include_top'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'include_top'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'include_top'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 21, in <module>
    obj.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\config\configuration.py", line 50, in get_prepare_base_model_config
    params_include_top=self.params.INCLUDE_TOP,
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'include_top'"
[2025-04-11 21:24:36,496: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 21:24:36,497: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:24:36,514: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:24:36,515: INFO: common: created directory at: artifacts]
[2025-04-11 21:24:36,515: INFO: common: created directory at: data_ingestion]
[2025-04-11 21:24:36,516: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 21:25:45,888: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 21:25:46,498: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 21:25:46,499: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 21:25:50,032: INFO: main: *******************]
[2025-04-11 21:25:50,033: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 21:25:50,034: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:25:50,036: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:25:50,036: INFO: common: created directory at: artifacts]
[2025-04-11 21:25:50,037: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 21:26:52,197: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 21:26:52,313: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 21:26:52,393: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-11 22:01:00,890: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:01:00,893: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:01:00,895: INFO: common: created directory at: artifacts]
[2025-04-11 22:01:00,897: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:01:01,377: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:01:38,441: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:01:38,445: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:01:38,446: INFO: common: created directory at: artifacts]
[2025-04-11 22:01:38,448: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:01:38,619: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:02:23,273: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:02:23,276: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:02:23,279: INFO: common: created directory at: artifacts]
[2025-04-11 22:02:23,282: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:02:23,445: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:02:33,915: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:02:33,918: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:02:33,920: INFO: common: created directory at: artifacts]
[2025-04-11 22:02:33,921: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:02:34,077: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:24:15,294: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 22:24:15,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:24:15,339: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:24:15,342: INFO: common: created directory at: artifacts]
[2025-04-11 22:24:15,343: INFO: common: created directory at: data_ingestion]
[2025-04-11 22:24:15,345: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 22:26:25,913: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 22:26:26,558: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 22:26:26,559: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 22:26:26,559: INFO: main: *******************]
[2025-04-11 22:26:26,559: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 22:26:26,560: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:26:26,561: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:26:26,562: INFO: common: created directory at: artifacts]
[2025-04-11 22:26:26,563: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 22:26:26,879: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:26:26,984: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:26:27,083: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-11 22:26:27,084: INFO: main: *******************]
[2025-04-11 22:26:27,084: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-11 22:26:27,085: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:26:27,087: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:26:27,088: INFO: common: created directory at: artifacts]
[2025-04-11 22:26:27,089: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:26:27,254: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:26:27,258: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 32, in <module>
    model_trainer.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\components\model_training.py", line 25, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\legacy\preprocessing\image.py", line 1138, in flow_from_directory
    return DirectoryIterator(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\legacy\preprocessing\image.py", line 453, in __init__
    for subdir in sorted(os.listdir(directory)):
                         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2025-04-11 22:28:30,608: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 22:28:30,609: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:28:30,610: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:28:30,611: INFO: common: created directory at: artifacts]
[2025-04-11 22:28:30,611: INFO: common: created directory at: data_ingestion]
[2025-04-11 22:28:30,611: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 22:29:43,420: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 22:29:43,964: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 22:29:43,964: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 22:29:43,964: INFO: main: *******************]
[2025-04-11 22:29:43,964: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 22:29:43,965: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:29:43,967: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:29:43,967: INFO: common: created directory at: artifacts]
[2025-04-11 22:29:43,967: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 22:29:44,224: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:29:44,400: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:29:44,495: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-11 22:29:44,496: INFO: main: *******************]
[2025-04-11 22:29:44,496: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-11 22:29:44,498: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:29:44,499: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:29:44,500: INFO: common: created directory at: artifacts]
[2025-04-11 22:29:44,501: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:29:44,656: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:29:44,682: ERROR: main: Training.train() missing 1 required positional argument: 'callback_list']
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 32, in <module>
    model_trainer.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
TypeError: Training.train() missing 1 required positional argument: 'callback_list'
[2025-04-11 22:34:04,028: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:34:04,032: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:34:04,036: INFO: common: created directory at: artifacts]
[2025-04-11 22:34:04,039: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:34:04,265: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:36:41,921: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:36:41,926: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:36:41,929: INFO: common: created directory at: artifacts]
[2025-04-11 22:36:41,931: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:36:42,091: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:36:59,774: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:36:59,777: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:36:59,779: INFO: common: created directory at: artifacts]
[2025-04-11 22:36:59,781: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:36:59,964: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:37:19,717: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:37:19,721: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:37:19,723: INFO: common: created directory at: artifacts]
[2025-04-11 22:37:19,724: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:37:19,893: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:38:01,399: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:38:01,404: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:38:01,406: INFO: common: created directory at: artifacts]
[2025-04-11 22:38:01,409: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:38:01,558: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:38:11,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:38:11,676: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:38:11,678: INFO: common: created directory at: artifacts]
[2025-04-11 22:38:11,679: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:38:11,856: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:39:57,725: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 22:39:57,727: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:39:57,728: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:39:57,728: INFO: common: created directory at: artifacts]
[2025-04-11 22:39:57,728: INFO: common: created directory at: data_ingestion]
[2025-04-11 22:39:57,729: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 22:41:05,454: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 22:41:06,089: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 22:41:06,089: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 22:41:06,089: INFO: main: *******************]
[2025-04-11 22:41:06,089: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 22:41:06,090: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:41:06,091: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:41:06,092: INFO: common: created directory at: artifacts]
[2025-04-11 22:41:06,092: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 22:41:06,482: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:41:06,639: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:41:06,742: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-11 22:41:06,742: INFO: main: *******************]
[2025-04-11 22:41:06,742: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-11 22:41:06,743: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:41:06,744: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:41:06,745: INFO: common: created directory at: artifacts]
[2025-04-11 22:41:06,746: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:41:06,895: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:41:06,920: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-12 09:48:52,296: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-12 09:48:52,298: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 09:48:52,300: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 09:48:52,301: INFO: common: created directory at: artifacts]
[2025-04-12 09:48:52,302: INFO: common: created directory at: data_ingestion]
[2025-04-12 09:48:52,303: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-12 09:49:34,917: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-12 09:49:35,868: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-12 09:49:35,868: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-12 09:49:35,868: INFO: main: *******************]
[2025-04-12 09:49:35,869: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-12 09:49:35,871: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 09:49:35,873: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 09:49:35,874: INFO: common: created directory at: artifacts]
[2025-04-12 09:49:35,875: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-12 09:49:36,591: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-12 09:49:36,962: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-12 09:49:37,193: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-12 09:49:37,194: INFO: main: *******************]
[2025-04-12 09:49:37,194: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-12 09:49:37,198: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 09:49:37,202: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 09:49:37,204: INFO: common: created directory at: artifacts]
[2025-04-12 09:49:37,205: INFO: common: created directory at: artifacts\training]
[2025-04-12 09:49:37,489: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 09:49:37,539: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-12 10:01:11,196: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:01:11,200: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:01:11,202: INFO: common: created directory at: artifacts]
[2025-04-12 10:01:11,204: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:01:11,567: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:01:19,575: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:01:19,578: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:01:19,580: INFO: common: created directory at: artifacts]
[2025-04-12 10:01:19,583: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:01:19,829: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:02:45,740: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:02:45,743: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:02:45,745: INFO: common: created directory at: artifacts]
[2025-04-12 10:02:45,748: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:02:45,949: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:08:39,779: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:08:39,782: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:08:39,784: INFO: common: created directory at: artifacts]
[2025-04-12 10:08:39,786: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:08:40,149: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:09:01,679: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:09:01,683: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:09:01,685: INFO: common: created directory at: artifacts]
[2025-04-12 10:09:01,687: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:09:01,862: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:11:24,102: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:11:24,107: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:11:24,110: INFO: common: created directory at: artifacts]
[2025-04-12 10:11:24,112: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:11:24,270: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:13:59,881: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:13:59,886: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:13:59,890: INFO: common: created directory at: artifacts]
[2025-04-12 10:13:59,891: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:14:00,066: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:15:29,992: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:15:29,996: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:15:29,999: INFO: common: created directory at: artifacts]
[2025-04-12 10:15:30,002: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:15:30,192: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:16:13,662: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:16:13,666: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:16:13,667: INFO: common: created directory at: artifacts]
[2025-04-12 10:16:13,670: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:16:13,838: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:20:20,157: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:20:20,160: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:20:20,160: INFO: common: created directory at: artifacts]
[2025-04-12 10:20:20,161: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:20:20,308: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:22:30,278: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:22:30,281: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:22:30,284: INFO: common: created directory at: artifacts]
[2025-04-12 10:22:30,285: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:23:06,977: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:23:06,980: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:23:06,982: INFO: common: created directory at: artifacts]
[2025-04-12 10:23:06,983: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:23:36,053: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:23:36,057: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:23:36,058: INFO: common: created directory at: artifacts]
[2025-04-12 10:23:36,060: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:23:36,264: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:30:55,241: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 03:15:11,741: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 03:15:11,742: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 03:15:11,744: INFO: common: created directory at: artifacts]
[2025-04-13 03:15:11,746: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-13 03:15:12,137: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 03:15:12,287: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 03:24:13,323: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-13 03:24:13,348: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 03:24:13,349: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 03:24:13,351: INFO: common: created directory at: artifacts]
[2025-04-13 03:24:13,351: INFO: common: created directory at: data_ingestion]
[2025-04-13 03:24:13,352: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-13 03:37:28,685: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-13 03:37:29,449: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-13 03:37:29,449: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-13 03:37:29,449: INFO: main: *******************]
[2025-04-13 03:37:29,449: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-13 03:37:29,460: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 03:37:29,474: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 03:37:29,474: INFO: common: created directory at: artifacts]
[2025-04-13 03:37:29,475: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-13 03:37:29,891: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 03:37:30,030: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 03:37:30,123: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-13 23:29:32,139: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:29:32,143: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:29:32,147: INFO: common: created directory at: artifacts]
[2025-04-13 23:29:32,151: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:33:53,785: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-13 23:33:53,786: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:33:53,788: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:33:53,788: INFO: common: created directory at: artifacts]
[2025-04-13 23:33:53,789: INFO: common: created directory at: data_ingestion]
[2025-04-13 23:33:53,789: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-13 23:35:42,263: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-13 23:35:42,879: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-13 23:35:42,880: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-13 23:35:42,880: INFO: main: *******************]
[2025-04-13 23:35:42,880: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-13 23:35:42,881: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:35:42,883: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:35:42,883: INFO: common: created directory at: artifacts]
[2025-04-13 23:35:42,884: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-13 23:35:43,427: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 23:35:43,587: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 23:35:43,679: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-13 23:37:17,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:37:17,333: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:37:17,335: INFO: common: created directory at: artifacts]
[2025-04-13 23:37:17,337: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:37:17,566: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-13 23:39:27,979: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:39:27,983: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:39:27,986: INFO: common: created directory at: artifacts]
[2025-04-13 23:39:27,989: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:39:28,230: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-13 23:39:30,125: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:39:30,127: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:39:30,128: INFO: common: created directory at: artifacts]
[2025-04-13 23:39:30,129: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:39:30,272: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-13 23:41:44,498: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:41:44,505: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:41:44,508: INFO: common: created directory at: artifacts]
[2025-04-13 23:41:44,510: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:41:44,663: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-13 23:42:52,027: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:42:52,031: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:42:52,032: INFO: common: created directory at: artifacts]
[2025-04-13 23:42:52,033: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:42:52,173: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-13 23:43:24,875: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:43:24,878: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:43:24,880: INFO: common: created directory at: artifacts]
[2025-04-13 23:43:24,883: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:43:25,034: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-13 23:49:46,698: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-14 09:30:40,327: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:30:40,329: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:30:40,329: INFO: common: created directory at: artifacts]
[2025-04-14 09:32:26,682: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:32:26,686: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:32:26,688: INFO: common: created directory at: artifacts]
[2025-04-14 09:32:26,690: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:32:27,346: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-14 09:33:26,114: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:33:26,116: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:33:26,118: INFO: common: created directory at: artifacts]
[2025-04-14 09:33:26,119: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:33:59,195: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:33:59,198: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:33:59,200: INFO: common: created directory at: artifacts]
[2025-04-14 09:33:59,202: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:34:56,610: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:34:56,614: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:34:56,617: INFO: common: created directory at: artifacts]
[2025-04-14 09:34:56,621: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:38:14,316: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:38:14,318: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:38:14,320: INFO: common: created directory at: artifacts]
[2025-04-14 09:40:45,819: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:40:45,822: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:40:45,825: INFO: common: created directory at: artifacts]
[2025-04-14 09:40:45,829: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:40:45,934: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-14 09:42:20,048: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:42:20,056: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:42:20,061: INFO: common: created directory at: artifacts]
[2025-04-14 09:42:20,062: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:42:20,251: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-14 09:44:50,468: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:44:50,474: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:44:50,476: INFO: common: created directory at: artifacts]
[2025-04-14 09:44:50,480: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:44:50,706: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-14 09:45:19,940: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:45:19,945: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:45:19,947: INFO: common: created directory at: artifacts]
[2025-04-14 09:45:19,949: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:45:20,115: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-14 09:46:39,426: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-14 09:46:39,427: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:46:39,428: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:46:39,429: INFO: common: created directory at: artifacts]
[2025-04-14 09:46:39,430: INFO: common: created directory at: data_ingestion]
[2025-04-14 09:46:39,430: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-14 09:48:14,575: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-14 09:48:15,179: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-14 09:48:15,180: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-14 09:48:15,180: INFO: main: *******************]
[2025-04-14 09:48:15,180: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-14 09:48:15,182: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:48:15,184: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:48:15,184: INFO: common: created directory at: artifacts]
[2025-04-14 09:48:15,185: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-14 09:48:15,558: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-14 09:48:15,708: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-14 09:48:15,809: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-14 09:48:15,810: INFO: main: *******************]
[2025-04-14 09:48:15,810: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-14 09:48:15,819: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:48:15,820: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:48:15,820: INFO: common: created directory at: artifacts]
[2025-04-14 09:48:15,821: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:48:15,978: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-14 09:48:16,015: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-14 23:24:10,451: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 23:24:10,469: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 23:24:10,471: INFO: common: created directory at: artifacts]
[2025-04-14 23:24:10,474: INFO: common: created directory at: artifacts\training]
[2025-04-14 23:24:11,039: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-14 23:25:04,983: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 23:25:04,987: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 23:25:04,990: INFO: common: created directory at: artifacts]
[2025-04-14 23:25:04,991: INFO: common: created directory at: artifacts\training]
[2025-04-14 23:25:05,355: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-14 23:25:22,039: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 23:25:22,050: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 23:25:22,053: INFO: common: created directory at: artifacts]
[2025-04-14 23:25:22,057: INFO: common: created directory at: artifacts\training]
[2025-04-14 23:25:22,330: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-14 23:28:01,399: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 23:28:01,426: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 23:28:01,437: INFO: common: created directory at: artifacts]
[2025-04-14 23:28:01,449: INFO: common: created directory at: artifacts\training]
[2025-04-14 23:28:02,062: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-14 23:28:24,072: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 23:28:24,076: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 23:28:24,078: INFO: common: created directory at: artifacts]
[2025-04-14 23:28:24,080: INFO: common: created directory at: artifacts\training]
[2025-04-14 23:28:24,294: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:35:31,558: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:35:31,572: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:35:31,574: INFO: common: created directory at: artifacts]
[2025-04-18 18:35:31,576: INFO: common: created directory at: artifacts\training]
[2025-04-18 18:35:32,021: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:36:20,062: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:36:20,070: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:36:20,074: INFO: common: created directory at: artifacts]
[2025-04-18 18:36:20,077: INFO: common: created directory at: artifacts\training]
[2025-04-18 18:36:20,344: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:37:19,131: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:37:19,133: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:37:19,135: INFO: common: created directory at: artifacts]
[2025-04-18 18:37:19,138: INFO: common: created directory at: artifacts\training]
[2025-04-18 18:37:19,303: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:38:42,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:38:42,297: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:38:42,298: INFO: common: created directory at: artifacts]
[2025-04-18 18:38:42,300: INFO: common: created directory at: artifacts\training]
[2025-04-18 18:38:42,433: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:40:42,743: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:40:42,761: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:40:42,770: INFO: common: created directory at: artifacts]
[2025-04-18 18:40:42,783: INFO: common: created directory at: artifacts\training]
[2025-04-18 18:40:42,989: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:41:41,365: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:41:41,367: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:41:41,369: INFO: common: created directory at: artifacts]
[2025-04-18 18:41:41,371: INFO: common: created directory at: artifacts\training]
[2025-04-18 18:41:41,518: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:49:31,488: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-18 18:49:31,489: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:49:31,490: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:49:31,491: INFO: common: created directory at: artifacts]
[2025-04-18 18:49:31,492: INFO: common: created directory at: data_ingestion]
[2025-04-18 18:49:31,493: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-18 18:50:34,017: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-18 18:50:34,694: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-18 18:50:34,694: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-18 18:50:34,695: INFO: main: *******************]
[2025-04-18 18:50:34,695: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-18 18:50:34,696: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:50:34,697: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:50:34,697: INFO: common: created directory at: artifacts]
[2025-04-18 18:50:34,698: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-18 18:50:35,172: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 18:50:35,306: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 18:50:35,428: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-18 19:00:42,592: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-18 19:00:42,593: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 19:00:42,594: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 19:00:42,595: INFO: common: created directory at: artifacts]
[2025-04-18 19:00:42,596: INFO: common: created directory at: data_ingestion]
[2025-04-18 19:00:42,596: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-18 19:01:50,185: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-18 19:01:50,800: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-18 19:01:50,800: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-18 19:01:50,800: INFO: main: *******************]
[2025-04-18 19:01:50,801: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-18 19:01:50,802: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 19:01:50,803: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 19:01:50,804: INFO: common: created directory at: artifacts]
[2025-04-18 19:01:50,805: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-18 19:01:51,176: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 19:01:51,304: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 19:01:51,409: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-18 19:04:40,725: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-18 19:04:40,761: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 19:04:40,763: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 19:04:40,764: INFO: common: created directory at: artifacts]
[2025-04-18 19:04:40,765: INFO: common: created directory at: data_ingestion]
[2025-04-18 19:04:40,766: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-18 19:06:45,327: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-18 19:06:45,953: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-18 19:06:45,953: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-18 19:06:45,954: INFO: main: *******************]
[2025-04-18 19:06:45,954: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-18 19:06:45,955: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 19:06:45,956: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 19:06:45,956: INFO: common: created directory at: artifacts]
[2025-04-18 19:06:45,957: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-18 19:06:45,958: ERROR: main: "'ConfigBox' object has no attribute 'updated_base_model_path'"]
Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 25, in <module>
    prepare_base_model.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\config\configuration.py", line 45, in get_prepare_base_model_config
    updated_base_model_path=Path(config.updated_base_model_path),
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'updated_base_model_path'"
[2025-04-18 19:13:48,837: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-18 19:13:48,864: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 19:13:48,865: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 19:13:48,866: INFO: common: created directory at: artifacts]
[2025-04-18 19:13:48,867: INFO: common: created directory at: data_ingestion]
[2025-04-18 19:13:48,867: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-18 19:15:14,051: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-18 19:15:14,693: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-18 19:15:14,693: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-18 19:15:14,693: INFO: main: *******************]
[2025-04-18 19:15:14,693: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-18 19:15:14,694: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 19:15:14,695: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 19:15:14,696: INFO: common: created directory at: artifacts]
[2025-04-18 19:15:14,697: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-18 19:15:14,958: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 19:15:15,069: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 19:15:15,176: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-18 20:43:49,912: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-18 20:43:49,914: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 20:43:49,916: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 20:43:49,916: INFO: common: created directory at: artifacts]
[2025-04-18 20:43:49,917: INFO: common: created directory at: data_ingestion]
[2025-04-18 20:43:49,917: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-18 20:45:39,784: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-18 20:45:40,453: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-18 20:45:40,453: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-18 20:45:40,453: INFO: main: *******************]
[2025-04-18 20:45:40,453: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-18 20:45:40,454: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 20:45:40,456: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 20:45:40,456: INFO: common: created directory at: artifacts]
[2025-04-18 20:45:40,456: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-18 20:45:40,725: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 20:45:40,834: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 20:45:40,933: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-18 20:55:35,587: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 20:55:35,590: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 20:55:35,592: INFO: common: created directory at: artifacts]
[2025-04-18 20:55:35,595: INFO: common: created directory at: artifacts\training]
[2025-04-18 20:55:35,942: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 20:55:54,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 20:55:54,335: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 20:55:54,337: INFO: common: created directory at: artifacts]
[2025-04-18 20:55:54,339: INFO: common: created directory at: artifacts\training]
[2025-04-18 20:55:54,487: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 21:18:00,893: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 21:18:00,897: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 21:18:00,900: INFO: common: created directory at: artifacts]
[2025-04-18 21:18:00,903: INFO: common: created directory at: artifacts\training]
[2025-04-18 21:18:01,184: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 21:18:29,783: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 21:18:29,786: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 21:18:29,788: INFO: common: created directory at: artifacts]
[2025-04-18 21:18:29,791: INFO: common: created directory at: artifacts\training]
[2025-04-18 21:18:30,048: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 21:21:00,299: WARNING: module_wrapper: From C:\Users\Prarthana\AppData\Local\Temp\ipykernel_23908\2490681004.py:5: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.
]
[2025-04-18 21:21:03,718: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 21:21:03,722: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 21:21:03,725: INFO: common: created directory at: artifacts]
[2025-04-18 21:21:03,727: INFO: common: created directory at: artifacts\training]
[2025-04-18 21:21:03,946: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 21:23:11,640: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 21:23:11,647: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 21:23:11,656: INFO: common: created directory at: artifacts]
[2025-04-18 21:23:11,664: INFO: common: created directory at: artifacts\training]
[2025-04-18 21:23:11,879: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 21:25:46,061: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 21:25:46,065: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 21:25:46,066: INFO: common: created directory at: artifacts]
[2025-04-18 21:25:46,068: INFO: common: created directory at: artifacts\training]
[2025-04-18 21:33:46,146: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
